### ISSUE TITLE
Use efm-langserver for shellcheck

### ISSUE THREAD

**Issue by kaihowl** [kaihowl/dotfiles#108]
https://github.com/mattn/efm-langserver

```
configs.efm.setup {
    init_options = {documentFormatting = true},
    settings = {
        rootMarkers = {".git/"},
    }
}
```

`brew install efm-langserver`

```
# file:~/.config/efm-langserver/config.yaml
version: 2
root-markers:
  - .git/
lint-debounce: 1s
tools:
  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'
languages:
  sh:
    - <<: *sh-shellcheck
```
